
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment:
      - DB_NAME=plantwiki
      - DB_CONNECTION=mongodb://harris:plantpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=harris
      - MONGO_INITDB_DATABASE=plantwiki
      - MONGO_INITDB_ROOT_PASSWORD=plantpass
volumes:
  dbdata: